package carte;

public enum Effetto {
	PERDERE_VITA, GUADAGNARE_VITA, AGGIUNGERE_MARCHIO_NERO, RIMUOVERE_MARCHIO_NERO,
	SCARTARE_CARTA, PESCARE_CARTA, GUADAGNARE_GETTONE, GUADAGNARE_ATTACCO, RIMUOVERE_ATTACCO, 
	EFFETTO_OPZIONALE, EFFETTO_NON_OPZIONALE;
}
