package carte;

public enum TipoEffetto {
	PERDERE_VITA, GUADAGNARE_VITA, AGGIUNGERE_MARCHIO_NERO, RIMUOVERE_MARCHIO_NERO,
	SCARTARE_CARTA, PESCARE_CARTA, GUADAGNARE_GETTONE, GUADAGNARE_ATTACCO, RIMUOVERE_ATTACCO, 
	SCELTA, DADO_TASSOROSSO, DADO_GRIFONDORO, DADO_CORVONERO, DADO_SERPEVERDE, SCONTO_ACQUISTO,
	RITIRA_DADO, ALLEATO_IN_MAZZO, INCANTESIMO_IN_MAZZO, OGGETTO_IN_MAZZO, COPIA_EFFETTO,
	NON_PESCARE_CARTE, NON_GUADAGNARE_VITA, NON_RIMUOVERE_MARCHI, NON_GUADAGNARE_ATTACCHI,
	NON_GUADAGNARE_GETTONI, SCARTA_INCANTESIMO, SCARTA_OGGETTO, SCARTA_ALLEATO, RIVELA_CARTA,
	RIVELA_NUOVO_EVENTO, ACQUISTO_CARTA, DADO_MALVAGIO, CERCA_ALLEATO, CERCA_INCANTESIMO,
	CERCA_OGGETTO, VITTORIA;
}
