package carte;

public enum TipoTrigger {
	NEMICO_SCONFITTO, AUTO_SCARTO, SCARTA_INCANTESIMO, GIOCA_ALLEATO, WEASLEY_IN_MANO, GIOCA_OGGETTO,
	SALUTE_MASSIMA, RIMOZIONE_MARCHIO_NERO, INCANTESIMI_GIOCATI, GUADAGNA_VITA, ATTACCHI_ASSEGNATI,
	STORDIMENTO, AGGIUNTA_MARCHIO_NERO, SCARTA_CARTA, ALLEATO_IN_MANO, ASSEGNA_PIU_ATTACCHI, 
	TUTTE_TIPOLOGIE, GIOCA_TUTTO, ACQUISTA_INCANTESIMO, RIVELA_NEMICO, 
	RIVELA_MORSMORDRE, SCARTA_GETTONI, COSTO_MAGGIORE_1;
}
