package gestoreEffetti;

public enum BersaglioEffetto {
	EROE_ATTIVO, SE_STESSO, TUTTI_GLI_EROI, EROI_NON_ATTIVI,EROE_SCELTO, EROE_ATTIVANTE, ALLEATO_GIOCATO, TUTTI_I_MALVAGI, LUOGO, SCELTA_MULTIPLA, MALVAGIO_SCELTO;
}
